### ISSUE TITLE
src/make error: src/kernel/common.h: error:  Unknown register name ‘ymm0’ appears in ‘asm’

### ISSUE THREAD

**Issue by HBKO** [NVSL/OptaneStudy#1]
Dear code author:
      When I compile the benchmark code, there is a compile error in src/common.h. The error is 
      src/kernel/common.h: Unknown register name 'ymm0' appears in 'asm'. I can't how to solve this error.
      Hope to get your answer.
                                                                                                          Kewen, He
                                                                                                                Nankai university

**Comment by TheNetAdmin** [comment]
`lattester` tool uses registers and instructions provided by AVX2 and AVX512 ([README](https://github.com/NVSL/OptaneStudy/tree/master/src#requirement)).

`ymm*` registers are from AVX2 and `zmm*` are from AVX512.

Maybe you can check if your CPU supports AVX2 and AVX512.

**Comment by HBKO** [comment]
The problem is fixed.
The reason why I can't complier is that my gcc version is too low. Using the gcc 7.3.1 is OK.

**Comment by xzy789** [comment]
Dear code author:
What is the meaning of stripe size in compilation options？I do not understand it.
Hope to get your answer.
Ziyue, Xu
Nankai university
