### ISSUE TITLE
Weird read bandwidth result

### ISSUE THREAD

**Issue by kongnull** [NVSL/OptaneStudy#8]
Ubuntu 18.04, Linux 4.13.0, 18 cores per socket, 6 interleaved Optane DIMMs.

When I ran subtests/40_sizebw.sh with op=0 for random read bandwidth, I got the follwing result (MB/s):

64B: 9750
128B: 18950
256B: 34530
512B: 35000
**1KB: 17000
2KB: 22500**
4KB: 28500
8KB: 31200
16KB: 32500

According to the paper, the lowest performance should be at 4KB.
However, I got weird result at 1KB and 2KB.
(The random write bandwidth result is the same with the paper)

**Comment by TheNetAdmin** [comment]
Have you tried to boost the CPU to a stable frequency and disable cache prefetcher?

Some script code that might be useful, from another project that is based on LATTester:

https://github.com/TheNetAdmin/LENS/blob/32f794321e1ba23983da94d88a7142a2c4b3868c/scripts/utils/launch.sh#L32-L39

**Comment by sheepx86** [comment]
Disabling the cache prefetcher requires `msr` module loaded (or compiled in the kernel). Could you also share the CPU model and the PMM size?

**Comment by kongnull** [comment]
I used the run.example.sh script, the CPU frequency is maximized and the cache prefetcher is disabled.

The CPU is Xeon Gold 6240M,
L2 cache : 1024K
L3 cache: 24344K

Each Optane DIMM is 256GB

**Comment by kongnull** [comment]
> 
> 
> Disabling the cache prefetcher requires `msr` module loaded (or compiled in the kernel). Could you also share the CPU model and the PMM size?

Wow, the problem solved after "modprobe msr"
Thanks

**Comment by sheepx86** [comment]
Thanks for the feedback!
